### PR TITLE
Create README.org

### PR DESCRIPTION
**Pull request by stardiviner**
add note about make org-pdfview integrate with Org-mode more seamless.

### CODE REVIEW

**Comment by markus1189** [comment]
Maybe it would be better to add it to the commentary section of `org-pdfview.el`, because then it should be visible in emacs `list-packages`.

**Comment by stardiviner** [comment]
@markus1189 It's ok, I don't know that because I use el-get. Should I create a new pul request?

**Comment by markus1189** [comment]
you can just `git commit --amend` the changed version and `push -f` to the `patch-1` ref and it will pick the new version.

**Comment by markus1189** [comment]
I ported your note to `org-pdfview.el`. Thanks!

**Pull request closed without merging**
