### PR TITLE
Added "++" syntax for height variable.

### PR DESCRIPTION
**Pull request by titaniumbones**
Feels a little clumsy to me, but seems to work for all cases.  Intended to address #5

### CODE REVIEW

**Comment by markus1189** [comment]
Thanks!

**Comment by sherter** [comment]
How do you use this to jump to annotations as described in #5? Do you have a specialized `org-pdfview-store-link`? And can I use this to highlight the annotation as pdfview does it when hitting SPC in the annotations list?

**Comment by fuxialexander** [comment]
@sherter you might want to try my adaptation ;-)
https://github.com/fuxialexander/org-pdftools

**Comment by markus1189** [comment]
@fuxialexander nice, I am currently not really using this feature anymore, would you want me to link to yours instead?

**Comment by fuxialexander** [comment]
@markus1189 That would be great! Thanks a lot!

**Pull request merged**
